#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 04, 2018 03:55:28 PM CEST  platform: Linux
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join / home spara Fisica Python DSP GUI upload_button.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family {Bitstream Vera Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family {Bitstream Vera Sans Mono} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1053x701+119+-1
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "PHASE TRACKING GUI"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo43 \
        -width 300 -height 200 -takefocus {} 
    vTcl:DefineAlias "$top.tNo43" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo43.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t0 \
        -padding 0 -sticky nsew -state normal -text LOAD -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo43.t0
    frame $site_4_0.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 115 \
        -highlightcolor black -width 975 
    vTcl:DefineAlias "$site_4_0.fra45" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra45
    label $site_5_0.lab47 \
        -activebackground {#841216} -activeforeground black \
        -background {#d8d582} -foreground {#000000} -highlightcolor black \
        -justify right -relief sunken -text {Load from file} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Search 
    vTcl:DefineAlias "$site_5_0.but39" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but39 <Button-1> {
        lambda e: Search_pressed(e)
    }
    text $site_5_0.tex43 \
        -background {#ffffff} -font TkTextFont -foreground black -height 26 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 256 \
        -wrap word 
    .top39.tNo43.t0.fra45.tex43 configure -font TkTextFont
    .top39.tNo43.t0.fra45.tex43 insert end text
    vTcl:DefineAlias "$site_5_0.tex43" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Delimiter: 
    vTcl:DefineAlias "$site_5_0.lab44" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable cont_delim 
    vTcl:DefineAlias "$site_5_0.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -image [vTcl:image:get_image [file join / home spara Fisica Python DSP GUI upload_button.png]] \
        -text Button 
    vTcl:DefineAlias "$site_5_0.but40" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but40 <Button-1> {
        lambda e: LoadFile_pressed(e)
    }
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Chunck: 
    vTcl:DefineAlias "$site_5_0.lab39" "Label8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable cont_chunck 
    vTcl:DefineAlias "$site_5_0.ent41" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab54 \
        -background {#d9d9d9} -foreground {#000000} \
        -textvariable upload_check 
    vTcl:DefineAlias "$site_5_0.lab54" "Label11" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab47 \
        -in $site_5_0 -x 320 -y 10 -width 251 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 60 -y 70 -anchor nw -bordermode ignore 
    place $site_5_0.tex43 \
        -in $site_5_0 -x 160 -y 70 -width 256 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab44 \
        -in $site_5_0 -x 443 -y 70 -width 76 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent45 \
        -in $site_5_0 -x 522 -y 70 -width 36 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 795 -y 30 -width 69 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab39 \
        -in $site_5_0 -x 584 -y 70 -width 50 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent41 \
        -in $site_5_0 -x 643 -y 70 -width 76 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab54 \
        -in $site_5_0 -x 812 -y 69 -width 36 -height 19 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra46 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 465 \
        -highlightcolor black -width 975 
    vTcl:DefineAlias "$site_4_0.fra46" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra46
    label $site_5_0.lab54 \
        -activebackground {#841216} -activeforeground black \
        -background {#d8d582} -foreground {#000000} -highlightcolor black \
        -justify right -relief sunken -text {Load from simulated data} 
    vTcl:DefineAlias "$site_5_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text DE 
    vTcl:DefineAlias "$site_5_0.lab39" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text TE 
    vTcl:DefineAlias "$site_5_0.lab40" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text PH 
    vTcl:DefineAlias "$site_5_0.lab41" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent43" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent44" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    frame $site_5_0.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 395 \
        -highlightcolor black -width 565 
    vTcl:DefineAlias "$site_5_0.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent46" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {number of points:} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent48 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent48" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent49 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent49" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent50" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -image [vTcl:image:get_image [file join / home spara Fisica Python DSP GUI upload_button.png]] \
        -text Button 
    vTcl:DefineAlias "$site_5_0.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but53 <Button-1> {
        lambda e: LoadSim_pressed(e)
    }
    place $site_5_0.lab54 \
        -in $site_5_0 -x 320 -y 20 -width 251 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 100 -anchor nw -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 20 -y 170 -anchor nw -bordermode ignore 
    place $site_5_0.lab41 \
        -in $site_5_0 -x 20 -y 240 -anchor nw -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 70 -y 100 -width 200 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent43 \
        -in $site_5_0 -x 70 -y 170 -width 200 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent44 \
        -in $site_5_0 -x 70 -y 240 -width 200 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.fra45 \
        -in $site_5_0 -x 400 -y 60 -width 565 -relwidth 0 -height 395 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent46 \
        -in $site_5_0 -x 300 -y 100 -width 66 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 20 -y 310 -anchor nw -bordermode ignore 
    place $site_5_0.ent48 \
        -in $site_5_0 -x 300 -y 170 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent49 \
        -in $site_5_0 -x 300 -y 240 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent50 \
        -in $site_5_0 -x 160 -y 308 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but53 \
        -in $site_5_0 -x 150 -y 360 -anchor nw -bordermode ignore 
    place $site_4_0.fra45 \
        -in $site_4_0 -x 20 -y 10 -width 975 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.fra46 \
        -in $site_4_0 -x 20 -y 130 -width 975 -relwidth 0 -height 465 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo43.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t1 \
        -padding 0 -sticky nsew -state normal -text CHANNELS -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo43.t1
    frame $site_4_1.fra55 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 275 \
        -highlightcolor black -width 455 
    vTcl:DefineAlias "$site_4_1.fra55" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra57 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 245 \
        -highlightcolor black -width 405 
    vTcl:DefineAlias "$site_4_1.fra57" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra58 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 270 \
        -highlightcolor black -width 460 
    vTcl:DefineAlias "$site_4_1.fra58" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra59 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 295 \
        -highlightcolor black -width 435 
    vTcl:DefineAlias "$site_4_1.fra59" "Frame7" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but42 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text REFRESH 
    vTcl:DefineAlias "$site_4_1.but42" "Button4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.but42 <Button-1> {
        lambda e: Refresh_pressed(e)
    }
    labelframe $site_4_1.lab43 \
        -foreground black -text {Lowpass FIlter} -background {#d9d9d9} \
        -height 105 -width 310 
    vTcl:DefineAlias "$site_4_1.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.lab43
    entry $site_5_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable freq_cut 
    vTcl:DefineAlias "$site_5_0.ent44" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable freq_samp 
    vTcl:DefineAlias "$site_5_0.ent45" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab46 \
        -background {#d9d9d9} -foreground {#000000} -text {Cut freq.:} 
    vTcl:DefineAlias "$site_5_0.lab46" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab47 \
        -background {#d9d9d9} -foreground {#000000} -text {Sampling freq.:} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label10" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che53 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -justify left -text Apply \
        -variable applyfilt 
    vTcl:DefineAlias "$site_5_0.che53" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent44 \
        -in $site_5_0 -x 114 -y 30 -width 96 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent45 \
        -in $site_5_0 -x 114 -y 60 -width 96 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab46 \
        -in $site_5_0 -x 14 -y 30 -width 57 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 13 -y 60 -width 93 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che53 \
        -in $site_5_0 -x 225 -y 46 -width 63 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_1.fra55 \
        -in $site_4_1 -x 80 -y 120 -width 430 -relwidth 0 -height 270 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra57 \
        -in $site_4_1 -x 510 -y 120 -width 430 -relwidth 0 -height 270 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra58 \
        -in $site_4_1 -x 80 -y 390 -width 430 -relwidth 0 -height 270 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra59 \
        -in $site_4_1 -x 510 -y 390 -width 430 -relwidth 0 -height 270 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but42 \
        -in $site_4_1 -x 90 -y 50 -anchor nw -bordermode ignore 
    place $site_4_1.lab43 \
        -in $site_4_1 -x 200 -y 10 -width 310 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo43 \
        -in $top -x 0 -y 10 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

