#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 08, 2018 11:31:00 AM CEST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_phase_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    GUI_phase_support.set_Tk_var()
    top = PHASE_TRACKING_GUI (root)
    GUI_phase_support.init(root, top)
    root.mainloop()

w = None
def create_PHASE_TRACKING_GUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    GUI_phase_support.set_Tk_var()
    top = PHASE_TRACKING_GUI (w)
    GUI_phase_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_PHASE_TRACKING_GUI():
    global w
    w.destroy()
    w = None


class PHASE_TRACKING_GUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1013x700+716+147")
        top.title("PHASE TRACKING GUI")
        top.configure(highlightcolor="black")
        top.protocol('WM_DELETE_WINDOW',GUI_phase_support.on_closing)



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.014, relheight=1.0, relwidth=1.0)
        self.TNotebook1.configure(width=300)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="LOAD",compound="left",underline="-1",)
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="CHANNELS",compound="left",underline="-1",)
        self.TNotebook1_t2 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(2, text="CHs PSD",compound="none",underline="-1",)

        self.Frame2 = Frame(self.TNotebook1_t0)
        self.Frame2.place(relx=0.02, rely=0.015, relheight=0.17, relwidth=0.964)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=975)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.328, rely=0.087, height=29, width=251)
        self.Label1.configure(activebackground="#841216")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#d8d582")
        self.Label1.configure(borderwidth="2")
        self.Label1.configure(justify=RIGHT)
        self.Label1.configure(relief=SUNKEN)
        self.Label1.configure(text='''Load from file''')

        self.Button1 = Button(self.Frame2)
        self.Button1.place(relx=0.031, rely=0.609, height=27, width=63)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Search''')
        self.Button1.bind('<Button-1>',lambda e:GUI_phase_support.Search_pressed(e))

        self.Text1 = Text(self.Frame2)
        self.Text1.place(relx=0.123, rely=0.609, relheight=0.226, relwidth=0.263)

        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=256)
        self.Text1.configure(wrap=WORD)

        self.Label3 = Label(self.Frame2)
        self.Label3.place(relx=0.41, rely=0.609, height=21, width=76)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(borderwidth="2")
        self.Label3.configure(text='''Delimiter:''')

        self.Entry1 = Entry(self.Frame2)
        self.Entry1.place(relx=0.492, rely=0.609,height=21, relwidth=0.037)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(textvariable=GUI_phase_support.cont_delim)

        self.Button3 = Button(self.Frame2)
        self.Button3.place(relx=0.913, rely=0.261, height=34, width=69)
        self.Button3.configure(activebackground="#d9d9d9")
        self._img1 = PhotoImage(file="./upload_button.png")
        self.Button3.configure(image=self._img1)
        self.Button3.configure(text='''Button''')
        self.Button3.bind('<Button-1>',lambda e:GUI_phase_support.LoadFile_pressed(e))

        self.Label8 = Label(self.Frame2)
        self.Label8.place(relx=0.554, rely=0.609, height=19, width=50)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(borderwidth="2")
        self.Label8.configure(text='''Chunck:''')

        self.Entry8 = Entry(self.Frame2)
        self.Entry8.place(relx=0.615, rely=0.609,height=21, relwidth=0.078)
        self.Entry8.configure(background="white")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(textvariable=GUI_phase_support.cont_chunck)

        self.Label11 = Label(self.Frame2)
        self.Label11.place(relx=0.933, rely=0.609, height=19, width=36)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(borderwidth="2")
        self.Label11.configure(textvariable=GUI_phase_support.upload_check)

        self.Checkbutton3 = Checkbutton(self.Frame2)
        self.Checkbutton3.place(relx=0.764, rely=0.348, relheight=0.183
                , relwidth=0.07)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''LO mix''')
        self.Checkbutton3.configure(variable=GUI_phase_support.lo_mix)

        self.Entry12 = Entry(self.Frame2)
        self.Entry12.place(relx=0.738, rely=0.609,height=21, relwidth=0.119)
        self.Entry12.configure(background="white")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(selectbackground="#c4c4c4")
        self.Entry12.configure(textvariable=GUI_phase_support.freq_lo)

        self.Label15 = Label(self.Frame2)
        self.Label15.place(relx=0.862, rely=0.609, height=19, width=19)
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(borderwidth="2")
        self.Label15.configure(text='''Hz''')

        self.Frame3 = Frame(self.TNotebook1_t0)
        self.Frame3.place(relx=0.02, rely=0.192, relheight=0.688, relwidth=0.964)

        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(width=975)

        self.Label2 = Label(self.Frame3)
        self.Label2.place(relx=0.328, rely=0.043, height=29, width=251)
        self.Label2.configure(activebackground="#841216")
        self.Label2.configure(activeforeground="white")
        self.Label2.configure(background="#d8d582")
        self.Label2.configure(borderwidth="2")
        self.Label2.configure(justify=RIGHT)
        self.Label2.configure(relief=SUNKEN)
        self.Label2.configure(text='''Load from simulated data''')

        self.Label4 = Label(self.Frame3)
        self.Label4.place(relx=0.021, rely=0.215, height=21, width=21)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(borderwidth="2")
        self.Label4.configure(text='''DE''')

        self.Label5 = Label(self.Frame3)
        self.Label5.place(relx=0.021, rely=0.366, height=21, width=20)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(borderwidth="2")
        self.Label5.configure(text='''TE''')

        self.Label6 = Label(self.Frame3)
        self.Label6.place(relx=0.021, rely=0.516, height=21, width=23)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(borderwidth="2")
        self.Label6.configure(text='''PH''')

        self.Entry2 = Entry(self.Frame3)
        self.Entry2.place(relx=0.072, rely=0.215,height=22, relwidth=0.205)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(textvariable=GUI_phase_support.eq_de)

        self.Entry3 = Entry(self.Frame3)
        self.Entry3.place(relx=0.072, rely=0.366,height=22, relwidth=0.205)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(textvariable=GUI_phase_support.eq_te)

        self.Entry4 = Entry(self.Frame3)
        self.Entry4.place(relx=0.072, rely=0.516,height=22, relwidth=0.205)
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(textvariable=GUI_phase_support.eq_ph)

        self.Frame1 = Frame(self.Frame3)
        self.Frame1.place(relx=0.41, rely=0.129, relheight=0.849, relwidth=0.579)

        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=565)

        self.Entry5 = Entry(self.Frame3)
        self.Entry5.place(relx=0.308, rely=0.215,height=21, relwidth=0.068)
        self.Entry5.configure(background="white")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(textvariable=GUI_phase_support.st_de)

        self.Label7 = Label(self.Frame3)
        self.Label7.place(relx=0.021, rely=0.667, height=21, width=101)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(borderwidth="2")
        self.Label7.configure(text='''number of points:''')

        self.point_num_entry = Entry(self.Frame3)
        self.point_num_entry.place(relx=0.164, rely=0.656, height=21
                , relwidth=0.068)
        self.point_num_entry.configure(background="white")
        self.point_num_entry.configure(font="TkFixedFont")
        self.point_num_entry.configure(selectbackground="#c4c4c4")
        self.point_num_entry.configure(textvariable=GUI_phase_support.point_num)

        self.Button2 = Button(self.Frame3)
        self.Button2.place(relx=0.154, rely=0.774, height=34, width=69)
        self.Button2.configure(activebackground="#d9d9d9")
        self._img2 = PhotoImage(file="./upload_button.png")
        self.Button2.configure(image=self._img2)
        self.Button2.configure(text='''Button''')
        self.Button2.bind('<Button-1>',lambda e:GUI_phase_support.LoadSim_pressed(e))

        self.Frame4 = Frame(self.TNotebook1_t1)
        self.Frame4.place(relx=0.079, rely=0.178, relheight=0.399
                , relwidth=0.425)
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(width=455)

        self.Frame5 = Frame(self.TNotebook1_t1)
        self.Frame5.place(relx=0.504, rely=0.178, relheight=0.399
                , relwidth=0.425)
        self.Frame5.configure(relief=GROOVE)
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief=GROOVE)
        self.Frame5.configure(width=405)

        self.Frame6 = Frame(self.TNotebook1_t1)
        self.Frame6.place(relx=0.079, rely=0.577, relheight=0.399
                , relwidth=0.425)
        self.Frame6.configure(relief=GROOVE)
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief=GROOVE)
        self.Frame6.configure(width=460)

        self.Frame7 = Frame(self.TNotebook1_t1)
        self.Frame7.place(relx=0.504, rely=0.577, relheight=0.399
                , relwidth=0.425)
        self.Frame7.configure(relief=GROOVE)
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief=GROOVE)
        self.Frame7.configure(width=435)

        self.Button4 = Button(self.TNotebook1_t1)
        self.Button4.place(relx=0.089, rely=0.074, height=27, width=79)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(text='''REFRESH''')
        self.Button4.bind('<Button-1>',lambda e:GUI_phase_support.Refresh_pressed(e))

        self.Labelframe1 = LabelFrame(self.TNotebook1_t1)
        self.Labelframe1.place(relx=0.554, rely=0.059, relheight=0.096
                , relwidth=0.356)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(text='''Lowpass FIlter''')
        self.Labelframe1.configure(width=360)

        self.Entry9 = Entry(self.Labelframe1)
        self.Entry9.place(relx=0.306, rely=0.462, height=21, relwidth=0.267
                , bordermode='ignore')
        self.Entry9.configure(background="white")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(textvariable=GUI_phase_support.freq_cut)

        self.Label9 = Label(self.Labelframe1)
        self.Label9.place(relx=0.056, rely=0.462, height=19, width=57
                , bordermode='ignore')
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(borderwidth="2")
        self.Label9.configure(text='''Cut freq.:''')

        self.Checkbutton1 = Checkbutton(self.Labelframe1)
        self.Checkbutton1.place(relx=0.722, rely=0.462, relheight=0.323
                , relwidth=0.175, bordermode='ignore')
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Apply''')
        self.Checkbutton1.configure(variable=GUI_phase_support.applyfilt)

        self.Label12 = Label(self.Labelframe1)
        self.Label12.place(relx=0.611, rely=0.462, height=21, width=21
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(borderwidth="2")
        self.Label12.configure(text='''Hz''')

        self.Label12 = Label(self.Labelframe1)
        self.Label12.place(relx=1.222, rely=0.308, height=19, width=19
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(borderwidth="2")
        self.Label12.configure(text='''Hz''')

        self.Labelframe2 = LabelFrame(self.TNotebook1_t1)
        self.Labelframe2.place(relx=0.208, rely=0.059, relheight=0.096
                , relwidth=0.297)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Add white noise''')
        self.Labelframe2.configure(width=300)

        self.Entry11 = Entry(self.Labelframe2)
        self.Entry11.place(relx=0.2, rely=0.462, height=21, relwidth=0.253
                , bordermode='ignore')
        self.Entry11.configure(background="white")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(textvariable=GUI_phase_support.pow_value)

        self.Label13 = Label(self.Labelframe2)
        self.Label13.place(relx=0.033, rely=0.462, height=19, width=36
                , bordermode='ignore')
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(borderwidth="2")
        self.Label13.configure(text='''PSD:''')

        self.Label14 = Label(self.Labelframe2)
        self.Label14.place(relx=0.467, rely=0.462, height=19, width=59
                , bordermode='ignore')
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(borderwidth="2")
        self.Label14.configure(text='''(V^2/Hz)''')

        self.Checkbutton2 = Checkbutton(self.Labelframe2)
        self.Checkbutton2.place(relx=0.7, rely=0.462, relheight=0.323
                , relwidth=0.2, bordermode='ignore')
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(text='''Apply''')
        self.Checkbutton2.configure(variable=GUI_phase_support.applynoise)

        self.Entry10 = Entry(self.TNotebook1_t1)
        self.Entry10.place(relx=0.475, rely=0.015,height=21, relwidth=0.095)
        self.Entry10.configure(background="white")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(textvariable=GUI_phase_support.freq_samp)

        self.Label10 = Label(self.TNotebook1_t1)
        self.Label10.place(relx=0.376, rely=0.015, height=19, width=93)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(borderwidth="2")
        self.Label10.configure(text='''Sampling freq.:''')

        self.Label12 = Label(self.TNotebook1_t1)
        self.Label12.place(relx=0.574, rely=0.015, height=19, width=19)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(borderwidth="2")
        self.Label12.configure(text='''Hz''')

        self.Frame9 = Frame(self.TNotebook1_t2)
        self.Frame9.place(relx=0.504, rely=0.178, relheight=0.399
                , relwidth=0.425)
        self.Frame9.configure(relief=GROOVE)
        self.Frame9.configure(borderwidth="2")
        self.Frame9.configure(relief=GROOVE)
        self.Frame9.configure(width=125)

        self.Frame10 = Frame(self.TNotebook1_t2)
        self.Frame10.place(relx=0.079, rely=0.577, relheight=0.399
                , relwidth=0.425)
        self.Frame10.configure(relief=GROOVE)
        self.Frame10.configure(borderwidth="2")
        self.Frame10.configure(relief=GROOVE)
        self.Frame10.configure(width=125)

        self.Frame11 = Frame(self.TNotebook1_t2)
        self.Frame11.place(relx=0.504, rely=0.577, relheight=0.399
                , relwidth=0.425)
        self.Frame11.configure(relief=GROOVE)
        self.Frame11.configure(borderwidth="2")
        self.Frame11.configure(relief=GROOVE)
        self.Frame11.configure(width=125)

        self.Frame8 = Frame(self.TNotebook1_t2)
        self.Frame8.place(relx=0.079, rely=0.178, relheight=0.399
                , relwidth=0.425)
        self.Frame8.configure(relief=GROOVE)
        self.Frame8.configure(borderwidth="2")
        self.Frame8.configure(relief=GROOVE)
        self.Frame8.configure(width=415)

        self.Button5 = Button(self.TNotebook1_t2)
        self.Button5.place(relx=0.465, rely=0.059, height=47, width=77)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(text='''REFRESH''')
        self.Button5.bind('<Button-1>',lambda e:GUI_phase_support.Refresh_PSD(e))






if __name__ == '__main__':
    vp_start_gui()



