#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 15, 2018 04:52:16 PM CEST  platform: Linux
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join . upload_button.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family {Bitstream Vera Sans} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family {Bitstream Vera Sans Mono} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Bitstream Vera Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1139x700+153+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "PHASE TRACKING GUI"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo43 \
        -width 300 -height 200 -takefocus {} 
    vTcl:DefineAlias "$top.tNo43" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo43.t0 \
        -background {#a8a8a8} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t0 \
        -padding 0 -sticky nsew -state normal -text LOAD -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo43.t0
    frame $site_4_0.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 115 \
        -highlightcolor black -width 995 
    vTcl:DefineAlias "$site_4_0.fra45" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra45
    label $site_5_0.lab47 \
        -activebackground {#841216} -activeforeground black \
        -background {#d8d582} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -justify right -relief sunken \
        -text {Load from file} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Search 
    vTcl:DefineAlias "$site_5_0.but39" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but39 <Button-1> {
        lambda e: Search_pressed(e)
    }
    text $site_5_0.tex43 \
        -background {#ffffff} -font TkTextFont -foreground black -height 26 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 256 \
        -wrap word 
    .top39.tNo43.t0.fra45.tex43 configure -font TkTextFont
    .top39.tNo43.t0.fra45.tex43 insert end text
    vTcl:DefineAlias "$site_5_0.tex43" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Delimiter: 
    vTcl:DefineAlias "$site_5_0.lab44" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable cont_delim 
    vTcl:DefineAlias "$site_5_0.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -image [vTcl:image:get_image [file join . upload_button.png]] \
        -text Button 
    vTcl:DefineAlias "$site_5_0.but40" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but40 <Button-1> {
        lambda e: LoadFile_pressed(e)
    }
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Chunck: 
    vTcl:DefineAlias "$site_5_0.lab39" "Label8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable cont_chunck 
    vTcl:DefineAlias "$site_5_0.ent41" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -textvariable upload_check 
    vTcl:DefineAlias "$site_5_0.lab54" "Label11" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che41 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {LO mix} -variable lo_mix 
    vTcl:DefineAlias "$site_5_0.che41" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable freq_lo 
    vTcl:DefineAlias "$site_5_0.ent43" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Hz 
    vTcl:DefineAlias "$site_5_0.lab45" "Label15" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Downsamp -variable downsamp 
    vTcl:DefineAlias "$site_5_0.che40" "Checkbutton4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable num_down 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text num 
    vTcl:DefineAlias "$site_5_0.lab43" "Label17" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab47 \
        -in $site_5_0 -x 320 -y 10 -width 251 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but39 \
        -in $site_5_0 -x 30 -y 70 -anchor nw -bordermode ignore 
    place $site_5_0.tex43 \
        -in $site_5_0 -x 120 -y 70 -width 256 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab44 \
        -in $site_5_0 -x 400 -y 70 -width 76 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent45 \
        -in $site_5_0 -x 480 -y 70 -width 36 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but40 \
        -in $site_5_0 -x 900 -y 30 -width 69 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab39 \
        -in $site_5_0 -x 540 -y 70 -width 50 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent41 \
        -in $site_5_0 -x 600 -y 70 -width 76 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab54 \
        -in $site_5_0 -x 910 -y 70 -width 36 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che41 \
        -in $site_5_0 -x 750 -y 10 -width 68 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent43 \
        -in $site_5_0 -x 706 -y 30 -width 116 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab45 \
        -in $site_5_0 -x 830 -y 30 -width 19 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che40 \
        -in $site_5_0 -x 750 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 747 -y 85 -width 36 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab43 \
        -in $site_5_0 -x 793 -y 84 -width 32 -height 19 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra46 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 465 \
        -highlightcolor black -width 995 
    vTcl:DefineAlias "$site_4_0.fra46" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra46
    label $site_5_0.lab54 \
        -activebackground {#841216} -activeforeground black \
        -background {#d8d582} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -justify right -relief sunken \
        -text {Load from simulated data} 
    vTcl:DefineAlias "$site_5_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text DE 
    vTcl:DefineAlias "$site_5_0.lab39" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text TE 
    vTcl:DefineAlias "$site_5_0.lab40" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text PH 
    vTcl:DefineAlias "$site_5_0.lab41" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable eq_de 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable eq_te 
    vTcl:DefineAlias "$site_5_0.ent43" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable eq_ph 
    vTcl:DefineAlias "$site_5_0.ent44" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    frame $site_5_0.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 395 \
        -highlightcolor black -width 545 
    vTcl:DefineAlias "$site_5_0.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable st_de 
    vTcl:DefineAlias "$site_5_0.ent46" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text {number of points:} 
    vTcl:DefineAlias "$site_5_0.lab47" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable point_num 
    vTcl:DefineAlias "$site_5_0.ent50" "point_num_entry" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -image [vTcl:image:get_image [file join . upload_button.png]] \
        -text Button 
    vTcl:DefineAlias "$site_5_0.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but53 <Button-1> {
        lambda e: LoadSim_pressed(e)
    }
    checkbutton $site_5_0.che46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Add Rand Noise} -variable ck_rand_de 
    vTcl:DefineAlias "$site_5_0.che46" "Checkbutton5" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Add Rand Noise} -variable ck_rand_te 
    vTcl:DefineAlias "$site_5_0.che49" "Checkbutton6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent51 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rand_te 
    vTcl:DefineAlias "$site_5_0.ent51" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Add Rand Noise} -variable ck_rand_ph 
    vTcl:DefineAlias "$site_5_0.che52" "Checkbutton7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent53 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rand_ph 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text (V^2/Hz)@1Hz 
    vTcl:DefineAlias "$site_5_0.lab55" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text (V^2/Hz)@1Hz 
    vTcl:DefineAlias "$site_5_0.lab56" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text (V^2/Hz)@1Hz 
    vTcl:DefineAlias "$site_5_0.lab57" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Tsamp 
    vTcl:DefineAlias "$site_5_0.lab58" "Label19" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text (s) 
    vTcl:DefineAlias "$site_5_0.lab59" "Label20" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but60 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {PHI PSD} 
    vTcl:DefineAlias "$site_5_0.but60" "Button8" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.but60 <Button-1> {
        lambda e: phipsd_pressed(e)
    }
    entry $site_5_0.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rand_de 
    vTcl:DefineAlias "$site_5_0.ent41" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab54 \
        -in $site_5_0 -x 320 -y 20 -width 251 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 79 -width 23 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 20 -y 151 -width 21 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab41 \
        -in $site_5_0 -x 20 -y 223 -width 22 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 70 -y 80 -width 200 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_5_0.ent43 \
        -in $site_5_0 -x 70 -y 151 -width 200 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_5_0.ent44 \
        -in $site_5_0 -x 70 -y 223 -width 200 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_5_0.fra45 \
        -in $site_5_0 -x 420 -y 60 -width 545 -relwidth 0 -height 395 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent46 \
        -in $site_5_0 -x 294 -y 310 -width 66 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 20 -y 310 -anchor nw -bordermode ignore 
    place $site_5_0.ent50 \
        -in $site_5_0 -x 140 -y 310 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but53 \
        -in $site_5_0 -x 150 -y 355 -width 69 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che46 \
        -in $site_5_0 -x 27 -y 110 -width 123 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.che49 \
        -in $site_5_0 -x 23 -y 180 -width 133 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent51 \
        -in $site_5_0 -x 160 -y 180 -anchor nw -bordermode ignore 
    place $site_5_0.che52 \
        -in $site_5_0 -x 30 -y 250 -width 123 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent53 \
        -in $site_5_0 -x 160 -y 250 -anchor nw -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 311 -y 110 -width 94 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 310 -y 180 -width 94 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab57 \
        -in $site_5_0 -x 310 -y 250 -width 94 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab58 \
        -in $site_5_0 -x 242 -y 310 -width 44 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab59 \
        -in $site_5_0 -x 369 -y 311 -width 18 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but60 \
        -in $site_5_0 -x 300 -y 410 -width 87 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent41 \
        -in $site_5_0 -x 160 -y 110 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra45 \
        -in $site_4_0 -x 20 -y 10 -width 995 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.fra46 \
        -in $site_4_0 -x 20 -y 150 -width 995 -relwidth 0 -height 465 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo43.t1 \
        -background {#a8a8a8} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t1 \
        -padding 0 -sticky nsew -state normal -text CHANNELS -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo43.t1
    frame $site_4_1.fra55 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_1.fra55" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra57 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_1.fra57" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra58 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_1.fra58" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_1.fra59 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_1.fra59" "Frame7" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text REFRESH 
    vTcl:DefineAlias "$site_4_1.but42" "Button4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.but42 <Button-1> {
        lambda e: Refresh_pressed(e)
    }
    labelframe $site_4_1.lab43 \
        -foreground black -text {Lowpass FIlter} -background {#d9d9d9} \
        -height 65 -highlightcolor black -width 360 
    vTcl:DefineAlias "$site_4_1.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.lab43
    entry $site_5_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable freq_cut 
    vTcl:DefineAlias "$site_5_0.ent44" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text {Cut freq.:} 
    vTcl:DefineAlias "$site_5_0.lab46" "Label9" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Apply -variable applyfilt 
    vTcl:DefineAlias "$site_5_0.che53" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Hz 
    vTcl:DefineAlias "$site_5_0.lab39" "Label12" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Hz 
    vTcl:DefineAlias "$site_5_0.lab40" "Label12" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent44 \
        -in $site_5_0 -x 110 -y 30 -width 96 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab46 \
        -in $site_5_0 -x 20 -y 30 -width 57 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che53 \
        -in $site_5_0 -x 260 -y 30 -width 63 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab39 \
        -in $site_5_0 -x 220 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 440 -y 20 -width 19 -height 19 -anchor nw \
        -bordermode ignore 
    labelframe $site_4_1.lab42 \
        -foreground black -text {Add white noise} -background {#d9d9d9} \
        -height 65 -highlightcolor black -width 300 
    vTcl:DefineAlias "$site_4_1.lab42" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.lab42
    entry $site_5_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable pow_value 
    vTcl:DefineAlias "$site_5_0.ent43" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text PSD: 
    vTcl:DefineAlias "$site_5_0.lab44" "Label13" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text (V^2/Hz) 
    vTcl:DefineAlias "$site_5_0.lab45" "Label14" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Apply -variable applynoise 
    vTcl:DefineAlias "$site_5_0.che46" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent43 \
        -in $site_5_0 -x 60 -y 30 -width 76 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab44 \
        -in $site_5_0 -x 10 -y 30 -width 36 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab45 \
        -in $site_5_0 -x 140 -y 30 -width 59 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che46 \
        -in $site_5_0 -x 210 -y 30 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    entry $site_4_1.ent49 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable freq_samp 
    vTcl:DefineAlias "$site_4_1.ent49" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text {Sampling freq.:} 
    vTcl:DefineAlias "$site_4_1.lab50" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 2 -foreground {#000000} \
        -highlightcolor black -text Hz 
    vTcl:DefineAlias "$site_4_1.lab52" "Label12" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.fra55 \
        -in $site_4_1 -x 10 -y 80 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra57 \
        -in $site_4_1 -x 570 -y 80 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra58 \
        -in $site_4_1 -x 10 -y 370 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.fra59 \
        -in $site_4_1 -x 570 -y 370 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but42 \
        -in $site_4_1 -x 130 -y 10 -anchor nw -bordermode ignore 
    place $site_4_1.lab43 \
        -in $site_4_1 -x 650 -y 7 -width 360 -relwidth 0 -height 65 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab42 \
        -in $site_4_1 -x 320 -y 7 -width 300 -relwidth 0 -height 65 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent49 \
        -in $site_4_1 -x 170 -y 50 -width 96 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab50 \
        -in $site_4_1 -x 70 -y 51 -width 93 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab52 \
        -in $site_4_1 -x 270 -y 50 -width 19 -height 19 -anchor nw \
        -bordermode ignore 
    frame $top.tNo43.t2 \
        -background {#a8a8a8} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t2" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t2 \
        -padding 0 -sticky nsew -state normal -text {CHs PSD} -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo43.t2
    frame $site_4_2.fra40 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_2.fra40" "Frame9" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_2.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_2.fra41" "Frame10" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_2.fra42 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_2.fra42" "Frame11" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_2.fra44 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 290 \
        -highlightcolor black -width 560 
    vTcl:DefineAlias "$site_4_2.fra44" "Frame8" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text REFRESH 
    vTcl:DefineAlias "$site_4_2.but40" "Button5" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.but40 <Button-1> {
        lambda e: Refresh_PSD(e)
    }
    place $site_4_2.fra40 \
        -in $site_4_2 -x 570 -y 70 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.fra41 \
        -in $site_4_2 -x 10 -y 360 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.fra42 \
        -in $site_4_2 -x 570 -y 360 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.fra44 \
        -in $site_4_2 -x 10 -y 70 -width 560 -relwidth 0 -height 290 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but40 \
        -in $site_4_2 -x 526 -y 10 -width 77 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo43.t3 \
        -borderwidth 2 -background {#a8a8a8} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo43.t3" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo43 add $top.tNo43.t3 \
        -padding 0 -sticky nsew -state normal -text RECOVERY -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo43.t3
    frame $site_4_3.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 355 \
        -highlightcolor black -width 520 
    vTcl:DefineAlias "$site_4_3.fra39" "Frame12" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_3.fra40 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 355 \
        -highlightcolor black -width 590 
    vTcl:DefineAlias "$site_4_3.fra40" "Frame13" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but41 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text TRACK 
    vTcl:DefineAlias "$site_4_3.but41" "Button6" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_3.but41 <Button-1> {
        lambda e: track_start(e)
    }
    label $site_4_3.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -textvariable check_track 
    vTcl:DefineAlias "$site_4_3.lab39" "Label16" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but44 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text PSD 
    vTcl:DefineAlias "$site_4_3.but44" "Button7" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_3.but44 <Button-1> {
        lambda e: psd_phi(e)
    }
    frame $site_4_3.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 295 \
        -highlightcolor black -width 500 
    vTcl:DefineAlias "$site_4_3.fra45" "Frame14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_3.ent39 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable in_de 
    vTcl:DefineAlias "$site_4_3.ent39" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_3.ent40 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable in_te 
    vTcl:DefineAlias "$site_4_3.ent40" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_3.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable in_ph 
    vTcl:DefineAlias "$site_4_3.ent42" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text De 
    vTcl:DefineAlias "$site_4_3.lab44" "Label21" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Start point} 
    vTcl:DefineAlias "$site_4_3.lab45" "Label22" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Te 
    vTcl:DefineAlias "$site_4_3.lab46" "Label23" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_3.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Ph 
    vTcl:DefineAlias "$site_4_3.lab47" "Label24" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_3.fra39 \
        -in $site_4_3 -x 10 -y 186 -width 520 -relwidth 0 -height 355 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.fra40 \
        -in $site_4_3 -x 540 -y 10 -width 590 -relwidth 0 -height 355 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but41 \
        -in $site_4_3 -x 60 -y 80 -width 97 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab39 \
        -in $site_4_3 -x 190 -y 90 -width 76 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but44 \
        -in $site_4_3 -x 430 -y 70 -width 87 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.fra45 \
        -in $site_4_3 -x 590 -y 370 -width 500 -relwidth 0 -height 295 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.ent39 \
        -in $site_4_3 -x 350 -y 60 -width 50 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.ent40 \
        -in $site_4_3 -x 350 -y 90 -width 50 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.ent42 \
        -in $site_4_3 -x 350 -y 120 -width 50 -relwidth 0 -height 21 \
        -anchor nw -bordermode ignore 
    place $site_4_3.lab44 \
        -in $site_4_3 -x 320 -y 60 -width 20 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab45 \
        -in $site_4_3 -x 320 -y 30 -width 76 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab46 \
        -in $site_4_3 -x 320 -y 92 -width 18 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_3.lab47 \
        -in $site_4_3 -x 320 -y 122 -width 19 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo43 \
        -in $top -x 0 -y 10 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

