#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 03, 2018 11:06:53 AM CEST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_phase_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    GUI_phase_support.set_Tk_var()
    top = PHASE_TRACKING_GUI (root)
    GUI_phase_support.init(root, top)
    root.mainloop()

w = None
def create_PHASE_TRACKING_GUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    GUI_phase_support.set_Tk_var()
    top = PHASE_TRACKING_GUI (w)
    GUI_phase_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_PHASE_TRACKING_GUI():
    global w
    w.destroy()
    w = None


class PHASE_TRACKING_GUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("941x637+168+116")
        top.title("PHASE TRACKING GUI")
        top.configure(highlightcolor="black")



        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.016, relheight=1.0, relwidth=1.0)
        self.TNotebook1.configure(width=300)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Page 1",compound="left",underline="-1",)
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Page 2",compound="left",underline="-1",)

        self.Frame2 = Frame(self.TNotebook1_t0)
        self.Frame2.place(relx=0.021, rely=0.016, relheight=0.188
                , relwidth=0.953)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=895)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.358, rely=0.087, height=29, width=251)
        self.Label1.configure(activebackground="#841216")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#d8d582")
        self.Label1.configure(justify=RIGHT)
        self.Label1.configure(relief=SUNKEN)
        self.Label1.configure(text='''Load from file''')

        self.Button1 = Button(self.Frame2)
        self.Button1.place(relx=0.067, rely=0.609, height=27, width=68)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Search''')
        self.Button1.bind('<Button-1>',lambda e:GUI_phase_support.Search_pressed(e))

        self.Text1 = Text(self.Frame2)
        self.Text1.place(relx=0.179, rely=0.609, relheight=0.226, relwidth=0.286)

        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=256)
        self.Text1.configure(wrap=WORD)

        self.Label3 = Label(self.Frame2)
        self.Label3.place(relx=0.503, rely=0.609, height=21, width=76)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Delimiter:''')

        self.Entry1 = Entry(self.Frame2)
        self.Entry1.place(relx=0.62, rely=0.609,height=21, relwidth=0.04)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(textvariable=GUI_phase_support.contEntry1)

        self.Button3 = Button(self.Frame2)
        self.Button3.place(relx=0.76, rely=0.348, height=34, width=69)
        self.Button3.configure(activebackground="#d9d9d9")
        self._img1 = PhotoImage(file="./upload_button.png")
        self.Button3.configure(image=self._img1)
        self.Button3.configure(text='''Button''')

        self.Frame3 = Frame(self.TNotebook1_t0)
        self.Frame3.place(relx=0.021, rely=0.228, relheight=0.677
                , relwidth=0.953)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(width=895)

        self.Label2 = Label(self.Frame3)
        self.Label2.place(relx=0.358, rely=0.048, height=29, width=251)
        self.Label2.configure(activebackground="#841216")
        self.Label2.configure(activeforeground="white")
        self.Label2.configure(background="#d8d582")
        self.Label2.configure(justify=RIGHT)
        self.Label2.configure(relief=SUNKEN)
        self.Label2.configure(text='''Load from simulated data''')

        self.Label4 = Label(self.Frame3)
        self.Label4.place(relx=0.022, rely=0.241, height=19, width=21)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''DE''')

        self.Label5 = Label(self.Frame3)
        self.Label5.place(relx=0.022, rely=0.41, height=19, width=19)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''TE''')

        self.Label6 = Label(self.Frame3)
        self.Label6.place(relx=0.022, rely=0.578, height=19, width=20)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(text='''PH''')

        self.Entry2 = Entry(self.Frame3)
        self.Entry2.place(relx=0.078, rely=0.241,height=21, relwidth=0.223)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="#c4c4c4")

        self.Entry3 = Entry(self.Frame3)
        self.Entry3.place(relx=0.078, rely=0.41,height=21, relwidth=0.223)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(selectbackground="#c4c4c4")

        self.Entry4 = Entry(self.Frame3)
        self.Entry4.place(relx=0.078, rely=0.578,height=21, relwidth=0.223)
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(selectbackground="#c4c4c4")

        self.Frame1 = Frame(self.Frame3)
        self.Frame1.place(relx=0.447, rely=0.193, relheight=0.783
                , relwidth=0.542)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=485)

        self.Entry5 = Entry(self.Frame3)
        self.Entry5.place(relx=0.335, rely=0.241,height=21, relwidth=0.074)
        self.Entry5.configure(background="white")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(selectbackground="#c4c4c4")

        self.Label7 = Label(self.Frame3)
        self.Label7.place(relx=0.022, rely=0.747, height=19, width=112)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(text='''number of points:''')

        self.Entry6 = Entry(self.Frame3)
        self.Entry6.place(relx=0.335, rely=0.41,height=21, relwidth=0.074)
        self.Entry6.configure(background="white")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(selectbackground="#c4c4c4")

        self.Entry7 = Entry(self.Frame3)
        self.Entry7.place(relx=0.335, rely=0.578,height=21, relwidth=0.074)
        self.Entry7.configure(background="white")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(selectbackground="#c4c4c4")

        self.Entry7 = Entry(self.Frame3)
        self.Entry7.place(relx=0.179, rely=0.735,height=21, relwidth=0.074)
        self.Entry7.configure(background="white")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(selectbackground="#c4c4c4")

        self.Button2 = Button(self.Frame3)
        self.Button2.place(relx=0.168, rely=0.867, height=34, width=69)
        self.Button2.configure(activebackground="#d9d9d9")
        self._img2 = PhotoImage(file="./upload_button.png")
        self.Button2.configure(image=self._img2)
        self.Button2.configure(text='''Button''')
        self.Button2.bind('<Button-1>',lambda e:GUI_phase_support.LoadSim_pressed(e))

        self.Frame4 = Frame(self.TNotebook1_t1)
        self.Frame4.place(relx=0.064, rely=0.131, relheight=0.383, relwidth=0.41)

        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(width=385)

        self.Frame4 = Frame(self.TNotebook1_t1)
        self.Frame4.place(relx=0.522, rely=0.131, relheight=0.383, relwidth=0.41)

        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(width=385)

        self.Frame4 = Frame(self.TNotebook1_t1)
        self.Frame4.place(relx=0.064, rely=0.571, relheight=0.383, relwidth=0.41)

        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(width=385)

        self.Frame4 = Frame(self.TNotebook1_t1)
        self.Frame4.place(relx=0.522, rely=0.571, relheight=0.383, relwidth=0.41)

        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(width=385)






if __name__ == '__main__':
    vp_start_gui()



